### ISSUE TITLE
subscribed rules periodically become ineffective

### ISSUE THREAD

**Issue by tglsf** [salarcode/SmartProxy#217]
subscribed rules periodically become ineffective, and the address that needs to go through the proxy does not go through the proxy. When clicking on the extension icon, the words "included in subscribed rules" are not displayed. This usually happens when the browser is started or after a period of use.
I have to go to the extension's settings page, update the subscribed rules manually and click save. (When I go to the settings page, the number of rule entries is displayed normally.)
I guess this may be caused by the failure of the automatic update of the rules. (In certain network environments, the list of rules also needs to be updated through a proxy.) If this is the case, the program should continue to use the list as it was before the update. (Or maybe this is not the case, just my guess. I don't know enough about computer technology to test it in detail.)

Thanks.
(I don't speak English, so the description of the options may not be accurate. I don't know what these setting items are called in English.)

Addendum: I'm using Firefox 100 and above on Windows; Firefox Nighity on Android has the same problem.

**Comment by scalpelx** [comment]
I had the same problem

**Comment by asypost** [comment]
> I had the same problem

me too

**Comment by salarcode** [comment]
What is the version of SmartProxy you all are using?

**Comment by scalpelx** [comment]
> What is the version of SmartProxy you all are using?

0.9.12

**Comment by JamYiz** [comment]
please update soon，current version has a lot questions

**Comment by JamYiz** [comment]
I also have this problem, it seriously affects the normal use

**Comment by salarcode** [comment]
Syncing issue should be fixed with version 1.0

**Comment by salarcode** [comment]
This should be fixed in version 1.0 please try there and let me know if this is still an issue

**Comment by scalpelx** [comment]
> This should be fixed in version 1.0 please try there and let me know if this is still an issue

This issue still exists when I turn on General Syncing. If I turn off the sync and refresh the subscribed rules again, it become normal.
version: 1.0.2, Chrome 109.0.5414.75, Edge 109.0.1518.61

**Comment by salarcode** [comment]
Please use Last used Proxy server in subscription list to see where it has failed

![image](https://user-images.githubusercontent.com/1272095/214798465-99f1015c-3343-42a3-8a43-5408c11a5ae0.png)

**Comment by scalpelx** [comment]
![无标题](https://user-images.githubusercontent.com/12198804/215013941-b8a6ac91-7551-4a74-bea1-f19555f0d131.png)

**Comment by salarcode** [comment]
> The issue occurs in Smart mode. if I switch to Always Enabled mode, it's normal. It seems like when auto update the subscription, it not use the previous rules or these rules have been cleared

Is https://raw.githubusercontent.com/ blocked in your country? That's the issue then add `raw.githubusercontent.com` to the list of rules then.

Everyone here if that's the issue for you do as above

**Comment by scalpelx** [comment]
`raw.githubusercontent.com` is already in the list. It seems when auto update the subscription, it not use the list of rules.

**Comment by salarcode** [comment]
Please use Firefox and enable the diagnostics and send the details to my email `salarcode [at] gmail.com`

Follow the instructions here
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

I won't be able help you otherwise.
