### ISSUE TITLE
Full backup restore fails in Chrome

### ISSUE THREAD

**Issue by Drommer** [salarcode/SmartProxy#81]
When trying to restore the full backup settings, we get an error. 
Also, the extension does not work when you start the browser until you switch to the "always on" mode (after that it works in any mode until the next restart of the browser).
Tested in a stable version of the Chrome browser and mobile Yandex Browser. Version 0.7.3 worked fine.

**Comment by salarcode** [comment]
"always on" issue should be fixed in 0.8.1.
Do you use "Restore Backup" button? what is the error message?

**Comment by Drommer** [comment]
A use Arch Linux and Chromium 74.0.3729.157 / Firefox Nightly, SmartProxy version 0.8.1.

On Firefox now all right. In Chromium the problem remains. When you start the browser, and during operation, the extension periodically just stops working. Switching modes solves the problem for a while.

Error message (in Chromium): "There was an error in restoring the backup". When restoring rules and servers separately, everything is successful. However, when importing servers, their names are not saved.

**Comment by salarcode** [comment]
The fix will release in 0.8.5
